### ISSUE TITLE
Please indent code in Temperature.java

### ISSUE THREAD

**Issue by Nickles255** [lzhengem/Java111b_Assignment5_Temperature#1]
Great job on getting the constructors started QD! Please indent everything within a class. 
Look at our previous projects.
No indentation will cause this code to be difficult to maintain.

**Comment by kryptonianS** [comment]
indented the codes.

**Comment by thisfinalcode** [comment]
please indent code that is within methods as well:

```
    public Temperature(){
    type ='C';
    degree= 0;
    }  
```

should look like this:
```
    public Temperature(){
        type ='C';
        degree= 0;
    }  
```

**Comment by kryptonianS** [comment]
okay, I indented the method according to the format you provided Lena. Let me know if its correct.
