### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment5_Temperature#10]
When testing the Temperature_Tester, there is a StringIndexOutOfBoundsException in the readInput() method. The it looks like input.next(); is collecting the user input, and then in the next line type does not read anything.

```
Sakura-Chan@Sakura MINGW64 ~/Desktop/java 111b/homework/assignment 5 (write_methods)
$ java Temperature_Tester

--------------------Testing part 1-------------------
Testing writeOutput at 40 degrees F
Temperature = 0.0 degrees .

readInput with writeOutput
Enter a temperature in degress
29.6
Enter 'F' (or 'f') for Fahrenheit or 'C' (or 'c') for Celsius:
f
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at Temperature.readInput(Temperature.java:52)
        at Temperature_Tester.main(Temperature_Tester.java:16)

```

try removing 

```
    input.next();
    //convert user input to a char
    type = input.nextLine().toUpperCase().charAt(0);

```
with

```
    //convert user input to a char
    type = input.next().toUpperCase().charAt(0);
```

**Comment by kryptonianS** [comment]
okay I changed the input.nextLine() to input.next().toUpperCase().charAt(0);. and I tested it and its working now

**Comment by kryptonianS** [comment]
okay i fixed it and tested it. The code is working now.
let me know if it still have issues.

Thank you

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by thisfinalcode** [comment]
Great, thanks QD. Part 2 is done and pushed to master.

Best,
Lena

**Comment by kryptonianS** [comment]
Awesome
