### ISSUE TITLE
Temperature not being formatted correctly

### ISSUE THREAD

**Issue by Nickles255** [lzhengem/Java111b_Assignment5_Temperature#14]
Performing test using Conner's program indicates degrees is not being formatted correctly. 
Please correct formatting in all write methods.

     Test case 7: writeC degrees C, original in F.
     Verify -46.2 degrees Celsius. 
     Temperature = -46.22222222222222 degrees C.

     Test case 13: getC method with original temperature in F.
     Verify -46.2
     -46.22222222222222_

Use format object to convert 
     import java.text.DecimalFormat;
     DecimalFormat df = new DecimalFormat("###,##0.0");

**Comment by thisfinalcode** [comment]
revised write methods and get methods. will push back to master
