### ISSUE TITLE
Method MUST DO INPUT VALIDATION FOR units

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment5_Temperature#17]
In her notes, it says that there must be input validations, meaning units other than C,c,F,f is should not be acceptable. Please update your methods if they take in unit arguments but does not do validations

9)  Implement a readInput() method to prompt user for degrees and type and then reads the values. NOTE: The Scanner class does not have a specific method for reading chars. 
Method MUST DO INPUT VALIDATION FOR units. Valid inputs are only: 'C' or 'F' or 'c' or 'f' for units. If user inputs lower case 'c' or 'f' these are acceptable and do not need to be changed to upper case

**Comment by Nickles255** [comment]
She stated the specific Method readInput() MUST DO INPUT VALIDATION.

I believe the set methods are assumed the programmer using the method knows what they are doing and did not require input validation. If it did, there would have to be an error catching mechanism which was not required.

**Comment by kryptonianS** [comment]
I put in a while loop inside the method to validate the unit the user put in

**Comment by thisfinalcode** [comment]
Awesome good job! It looks good to me, hows testing for you guys?

**Comment by kryptonianS** [comment]
Pretty good, tested over and over and looks good to me.
