### ISSUE TITLE
3 problems identified in ReadInPut method.

### ISSUE THREAD

**Issue by Nickles255** [lzhengem/Java111b_Assignment5_Temperature#2]
1. rename ReadInPut method to readInput (do we agree methods should start with a lower case and should be snake case?) 
btw TemperatureTester.Java which is what the instructor is testing our code with contains name of method to use. t1.readInput();

2. please prompt user before requesting data entry or else you just see an empty cursor and user will not know what to do. 

3. Should Scanner input = new Scanner(System.in) be within the class instead of in the method?  
When we need to create the set methods we can use the shared class scanner instead of having to create a new one for each method.

**Comment by thisfinalcode** [comment]
yea lets agree to do snakecase, and also for indentation use 2 spaces.

**Comment by kryptonianS** [comment]
I renamed the ReadInput to readInput.
I placed the scanner within the class, and added a prompt statement in the readInput method to ask  users for input.
