### ISSUE TITLE
dont need 'this'

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment5_Temperature#4]
were there instructions to use 'this' in the project? if not, it might be better not to use it because the professor mentioned in class that it is not necessary and it clogs the code

**Comment by kryptonianS** [comment]
i was kinda following an example that i found online in making the constructor LOL

**Comment by thisfinalcode** [comment]
i think u need to know when to use 'this' and when not to.... if the parameters have the same name, then you will need to use this, so if u are removing 'this' then you will need to change the parameter name

**Comment by kryptonianS** [comment]
I removed the "this" on the constructor
