### ISSUE TITLE
Would like to create private function to convertTemp

### ISSUE THREAD

**Issue by Nickles255** [lzhengem/Java111b_Assignment5_Temperature#6]
I want to write function in Temperature class:

Private double convertTemp(double p_degrees, char from_type, char to_type)

   if from_type = to_type then return p_degrees
   if from_type = 'F' and then_type = 'C' then return  (p_degrees - 32)/1.8
   if from_type = 'C' and then_type = 'F' then return  (p_degrees * 1.8) + 32

This will perform the conversion without duplicating code.
Please approve suggestion if you agree to this suggestion.

**Comment by thisfinalcode** [comment]
sounds good

**Comment by Nickles255** [comment]
Since the master has not been updated to include Temperature.java ... Please paste this private function into your code to centralize conversion of temperatures.

  // conversion function to convert degree parameter between Farenheit and Celcius
  private double convertTemp(double p_degrees, char from_type, char to_type){
      double out_degree = 0;
      from_type = Character.toUpperCase(from_type);
      to_type = Character.toUpperCase(to_type);
      if (from_type == to_type) {
         out_degree = p_degrees;
      } else {if (from_type == 'C' && to_type == 'F'){
                  out_degree = (p_degrees * 1.8) + 32;
              } else {if (from_type == 'F' && to_type == 'C'){
                          out_degree = (p_degrees - 32)/1.8;
                      }
                }
          
      }
      return out_degree;
  }
