### ISSUE TITLE
Char type[]

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment5_Temperature#8]
What is this line doing?

char type[]=input.next().toCharArray();

This returns an array for type right? Is that what we want

**Comment by kryptonianS** [comment]
that converts the input from the scanner to a char type.

**Comment by thisfinalcode** [comment]
it returns an array of char type, not char type:

https://www.tutorialspoint.com/java/java_string_tochararray.htm

**Comment by Nickles255** [comment]
I would suggest the code below. It takes a character type and also forces it into upper case so we don't have to check for both upper and lower case values.


type = scan.nextLine().toUpperCase().charAt(0);

**Comment by kryptonianS** [comment]
oh

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kryptonianS** [comment]
my mistake again, anyways i just changed it.
