### ISSUE TITLE
scan variable is not found

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment5_Temperature#9]
Please use the correct name for the scanner variable. it is best practice to make sure the code can compile
```
$ javac Temperature.java
Temperature.java:52: error: cannot find symbol
    type = scan.nextLine().toUpperCase().charAt(0);
           ^
  symbol:   variable scan
  location: class Temperature
1 error

```

**Comment by kryptonianS** [comment]
Oops that was my mistake, i sorta copied the scanner code that ken provided me and didnt realize it was a different variable. I changed to input for the scanner
